[package]
name = "cebolinha"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "worker"
path = "src/worker.rs"

[dependencies]
serde_json = "1.0"
redis = "0.27"
regex = "1.10"
chrono = "0.4"
ureq = "2.10"

[profile.release]
opt-level = 2
lto = "thin"
