services:
  api01: &api
    build:
      context: .
      target: asm-api
    container_name: api01
    hostname: api01
    networks:
      payment-processor:
      backend:
        ipv4_address: 172.20.0.3
    depends_on:
      redis:
        condition: service_healthy
      worker:
        condition: service_started

  api02: 
    <<: *api
    container_name: api02
    hostname: api02
    networks:
      payment-processor:
      backend:
        ipv4_address: 172.20.0.4

  worker:
    build:
      context: .
      target: go-worker
    container_name: worker
    hostname: worker
    command: worker
    networks:
      payment-processor:
      backend:
        ipv4_address: 172.20.0.5
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    networks:
      backend:
        ipv4_address: 172.20.0.2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    networks:
      backend:
        ipv4_address: 172.20.0.6
    depends_on:
      - redis
      - api01
      - api02
      - worker

networks:
  payment-processor:
    external: true
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
